/* BEFORE STARTING THE SAS PROGRAMMIMNG */
/* WE MUST KNOW ABOUT THE SHORTCUT KEYS */
/*  */
/* TO COMMENT - CTRL+? */
/* TO UNCOMMENT - CTRL+? */

/* ABCDE */

/* LETS START WITH SAS */

/* SAS- SAS STANDS FOR STATISTICAL ANALYSIS SYSTEM */

/* SAS HAS MANY COMPONENTS */
/* 1. SAS IS FOR DBMS AND PROGRAMMING */
/* 2. SAS IS FOR BUSINESS INTELLIGENCE AND DATA WAREHOUSING */
/* 3. SAS IS FOR VISUAL ANALYTICS */
/* 4. SAS IS FOR DATA MINING (PREDICTIVE ANALYTICS,ML,DL,AI) */

/* HOW TO START WITH SAS */
/* STEP1- GET LOG IN TO SAS CLOUD PLATFORM */
/* STEP2- LEARN SAS PROGRAMMINGS */
/* STEP3- LEARN SAS DATA MINING TECHNIQUES */

/* ABOUT SAS PROGRAMMING? */

/* SAS PROGRAMMING HAS BEEN DIVIDED INTO 2 PARTS */
/* 1. BASE SAS PROGRAMMING (PROGRAMMING-1 AND PROGRAMMING-2) */
/* 2. ADVANCED SAS PROGRAMMING (SAS SQL AND SAS MACRO) */


/* SAS JARGONS- */

/* IN SQL- WE CALL DATABASE - IN SAS WE CALL LIBRARY */
/* IN SQL- WE CALL TABLES - IN SAS WE CALL DATASETS */
/* IN SQL WE CALL COLUMNS - IN SAS WE CALL VARIABLES */
/* IN SQL WE CALL RECORDS - IN SAS WE CALL OBSERVATIONS */

/* LETS DO SAS PROGRAMMING */

DATA STU_ENQ;
INPUT STU_ID $ STU_NAME $ AGE GENDER $ EDUCATION $ DATE_OF_ENQ COURSE $;
INFORMAT DATE_OF_ENQ MMDDYY10.;
FORMAT DATE_OF_ENQ MMDDYY10.;
CARDS;
S1 ASHOK 35 MALE BTECH 01/23/2023 MPIDS
S2 AJIT 30 MALE BCA 01/27/2023 MPIDS
S3 ARCHANA 26 FEMALE BTECH 01/30/2023 MPIDS
;
RUN;

DATA STU_ENQ_ALL;
INPUT STU_ID $ STU_NAME $ AGE GENDER $ EDUCATION $ OCCUPATION $ DATE_OF_ENQ COURSE $;
INFORMAT DATE_OF_ENQ MMDDYY10.;
FORMAT DATE_OF_ENQ MMDDYY10.;
CARDS;
S1 DEEPTI 30 FEMALE BTECH IT 01-01-1960 MPIDS
S2 SUPRABHA 29 FEMALE BTECH IT 01-01-1959 MPIDS
S3 SASMITA 29 FEMALE BTECH IT 01-01-1961 MPIDS
S4 SOUVIK 34 MALE BTECH IT 04-02-2021 ADA
S5 SUMESH 31 MALE BTECH IT 05-02-2021 ADA
S6 PRATYUSH 31 MALE BTECH IT 06-02-2021 ADA
S7 PRADEEBA 27 FEMALE BTECH IT 07-02-2021 ADA
S8 MANISH 28 MALE MCA IT 08-02-2021 DAS
S9 PRITHVI 29 MALE MCA IT 09-02-2021 DAS
S10 ARPITA 31 FEMALE MCA IT 10-02-2021 DAS
;
RUN;

/* EXPLAINING THE SAS PROGRAM */

DATA STU_ENQ_ALL;
/* DATA STATEMENT IS USED TO CREATE THE DATASET . EVERY STATEMENT IN SAS ENDS WITH SEMICOLON*/
INPUT STU_ID $ STU_NAME $ AGE GENDER $ EDUCATION $ OCCUPATION $ DATE_OF_ENQ COURSE $;
/* INPUT STATEMENT TO CRAETE THE COLUMN INPUT. ANY COLUMN NAME OR VARIABLE NAME FOLLOWED $ SYMBOL REPRESENTS TO CHARACTER VARIABLE */
INFORMAT DATE_OF_ENQ MMDDYY10.;
/* INFORMAT STATEMENT TO READ THE DATA INTO SAS FORMAT */
FORMAT DATE_OF_ENQ MMDDYY10.;
/* FORMAT STATEMENT TO WRITE THE DATA INTO SAS FORMAT */
CARDS;
S1 DEEPTI 30 FEMALE BTECH IT 01-01-1960 MPIDS
S2 SUPRABHA 29 FEMALE BTECH IT 01-01-1959 MPIDS
S3 SASMITA 29 FEMALE BTECH IT 01-01-1961 MPIDS
S4 SOUVIK 34 MALE BTECH IT 04-02-2021 ADA
S5 SUMESH 31 MALE BTECH IT 05-02-2021 ADA
S6 PRATYUSH 31 MALE BTECH IT 06-02-2021 ADA
S7 PRADEEBA 27 FEMALE BTECH IT 07-02-2021 ADA
S8 MANISH 28 MALE MCA IT 08-02-2021 DAS
S9 PRITHVI 29 MALE MCA IT 09-02-2021 DAS
S10 ARPITA 31 FEMALE MCA IT 10-02-2021 DAS
;
/* CARDS STATEMENT TO PUT TEMPORAY DATA FOR CREATING ANY DATASETS */
RUN;
/* RUN STATEMENT TO EXECUTE THE PROGRAM */

/* WE JUST COMPLETED STATEMENTS SUCH AS */
/* 1. DATA STATEMENT */
/* 2. INPUT STATEMENT */
/* 3. INFORMAT STATEMENT */
/* 4. FORMAT STATEMENT */
/* 5. CARDS STATEMENT */
/* 6. RUN STATEMENT */

/* TO PRINT THE RESULT OF A DATASET */
PROC PRINT DATA=STU_ENQ_ALL;
RUN;
/* IN THIS ABOVE PROC PRINT IS A STATEMENT TO PRINT THE OUTPUT OF A DATASET INTO THE RESULT WINDOW */

/* SINCE WE HAVE CREATED A DATASET, WE RAN THE PROGRAM, WE SAW THE OUTPUT AND THE RESULT */
/* WE MUST UNDERSTAND SAS WINDOWS NOW */

/* 1. CODE WINDOW - TO WRITE SAS SYNTAXES */
/* 2. LOG WINDOW - TO CHECK ERROR,WARNINGS AND NOTES OR COMMENTS*/
/* 3. RESULTS - TO PRINT THE OUTPUT OF A DATASET */
/* 4. OUTPUT - TO SHOW THE DATASETS VARIABLES AND THE VALUES*/
/* 5. EXPLORER WINDOW - TO NAVIGATE YOUR DATASETS AND THE LIBRARIES*/


DATA STU_ENQ_ALL;
INPUT STU_ID $ STU_NAME $ AGE GENDER $ EDUCATION $ OCCUPATION $ DATE_OF_ENQ COURSE $;
INFORMAT DATE_OF_ENQ MMDDYY10.;
FORMAT DATE_OF_ENQ MMDDYY10.;
CARDS;
S1 DEEPTI 30 FEMALE BTECH IT 01-01-1960 MPIDS
S2 SUPRABHA 29 FEMALE BTECH IT 01-01-1959 MPIDS
S3 SASMITA 29 FEMALE BTECH IT 01-01-1961 MPIDS
S4 SOUVIK 34 MALE BTECH IT 04-02-2021 ADA
S5 SUMESH 31 MALE BTECH IT 05-02-2021 ADA
S6 PRATYUSH 31 MALE BTECH IT 06-02-2021 ADA
S7 PRADEEBA 27 FEMALE BTECH IT 07-02-2021 ADA
S8 MANISH 28 MALE MCA IT 08-02-2021 DAS
S9 PRITHVI 29 MALE MCA IT 09-02-2021 DAS
S10 ARPITA 31 FEMALE MCA IT 10-02-2021 DAS
;
RUN;


PROC PRINT DATA=STU_ENQ_ALL;
RUN;

/* IN THIS ABOVE SAS PROGRMMAING, WE SEE  */
/* SAS PROGRAMMING IS DIVIDED INTO 2 PARTS */
/* 1. SAS DATA STEP - TO CREATE THE DATASET*/
/* 2. SAS PROC STEP - TO PRINT THE OUTPUT OF A DATASET*/

/* 1. SAS DATA STEP */
DATA STU_ENQ_ALL;
INPUT STU_ID $ STU_NAME $ AGE GENDER $ EDUCATION $ OCCUPATION $ DATE_OF_ENQ COURSE $;
INFORMAT DATE_OF_ENQ MMDDYY10.;
FORMAT DATE_OF_ENQ MMDDYY10.;
CARDS;
S1 DEEPTI 30 FEMALE BTECH IT 01-01-1960 MPIDS
S2 SUPRABHA 29 FEMALE BTECH IT 01-01-1959 MPIDS
S3 SASMITA 29 FEMALE BTECH IT 01-01-1961 MPIDS
S4 SOUVIK 34 MALE BTECH IT 04-02-2021 ADA
S5 SUMESH 31 MALE BTECH IT 05-02-2021 ADA
S6 PRATYUSH 31 MALE BTECH IT 06-02-2021 ADA
S7 PRADEEBA 27 FEMALE BTECH IT 07-02-2021 ADA
S8 MANISH 28 MALE MCA IT 08-02-2021 DAS
S9 PRITHVI 29 MALE MCA IT 09-02-2021 DAS
S10 ARPITA 31 FEMALE MCA IT 10-02-2021 DAS
;
RUN;

/* 2. SAS PROC STEP */
PROC PRINT DATA=STU_ENQ_ALL;
RUN;

/* LETS DO CREATE ANOTHER DATASET FROM EXTERNAL FIXED FORMAT DATA FILE */


DATA STAFF;
INFILE '/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/a1.EMPLIST FM.txt';
INPUT LAST_NAME $ 1-20 FIRST_NAME $ 21-30 EMP_CODE $ 31-35 JOBTITLE $ 36-43 DOJ SALARY 54-59;
INFORMAT DOJ MMDDYY8.;
FORMAT DOJ MMDDYY10. SALARY DOLLAR12.;
RUN;

PROC PRINT DATA=STAFF;
RUN;

/* IN THIS ABOVE PROGRAM, EXAPLAIN THE STATEMENTS */

DATA STAFF;
/* DATA STATEMENT TO CREATE THE DATASET-STAFF. AND EVERY STATEMENT ENDS WITH SEMICOLON */
INFILE '/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/a1.EMPLIST FM.txt';
/* INFILE STATEMENT TO GET THE EXTERNAL FILE PATH TO READ DATA */
INPUT LAST_NAME $ 1-20 FIRST_NAME $ 21-30 EMP_CODE $ 31-35 JOBTITLE $ 36-43 DOJ SALARY 54-59;
/* INPUT STATEMENT TO DEFINE COLUMN INPUTS. $ 1-20 REPRESENT THE LENGTH OF THE VARIABLE TO BE READ FROM THE DATA FILE */
INFORMAT DOJ MMDDYY8.;
/* INFORMAT STATEMENT TO READ DATA INTO SAS FORMAT */
FORMAT DOJ MMDDYY10. SALARY DOLLAR12.;
/* FORMAT STATEMENT TO WRITE DATA INTO SAS FORMAT */
RUN;
/* RUN STATEMENT TO EXECUTE THE PROGRAM */

PROC PRINT DATA=STAFF;
RUN;
/* PROC PRINT STATEMENT TO PRINT TEH OUTPUT OF A DATASET IN THE RESULTS WINDOW */


/* EXPLAIN THE SAS PROGRAMMING STEPS */

/* DATA STEP */
DATA STAFF;
INFILE '/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/a1.EMPLIST FM.txt';
INPUT LAST_NAME $ 1-20 FIRST_NAME $ 21-30 EMP_CODE $ 31-35 JOBTITLE $ 36-43 DOJ SALARY 54-59;
INFORMAT DOJ MMDDYY8.;
FORMAT DOJ MMDDYY10. SALARY DOLLAR12.;
RUN;

/* PROC STEP */
PROC PRINT DATA=STAFF;
RUN;

/* LETS TALK ABOUT SAS LIBRARIES */
/* SAS LIBRARIES ARE 3 TYPES */
/* 1. PERMANT LIBRAY - SASUSER AND SASHELP*/
/* 2. TEMPORARY LIBRAY - WORK LIBRARY */
/* 3. USER DEFINED LIBRARY - LIBRAY THAT HAS BEEN DEFINED BY THE USER */

/* TO KEEP DATASETS INTO A USER DEFINED LIBRARY , WE MUST USE */

LIBNAME LIBREF <PATH>;
RUN;

LIBNAME SSN1 '/home/debendra330/BATCH_202301/SESSION_1/A3.SAS_DATASETS';
RUN;

DATA SSN1.STAFF;
INFILE '/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/a1.EMPLIST FM.txt';
INPUT LAST_NAME $ 1-20 FIRST_NAME $ 21-30 EMP_CODE $ 31-35 JOBTITLE $ 36-43 DOJ SALARY 54-59;
INFORMAT DOJ MMDDYY8.;
FORMAT DOJ MMDDYY10. SALARY DOLLAR12.;
RUN;

PROC PRINT DATA=SSN1.STAFF;
RUN;

/* AFTER THIS PROGRAM, WE UNDERSTAND THAT SAS DATASET EXTENSION IS */
/* .SAS7BDAT */
/* SAS PROGRAMMING EXTENSION */
/* .SAS */

/* WHEN WE CRAETED A LIBRAY NAME, WE CALL THIS AS SSN1 */

/* ARE WE FOLLOWING ANY CRITERIA FOR CREATING A LIBRAY NAME? */
/* ============================================================== */

/* YES, TO CREATE A LIBRAY , WE MUST FOLLOW THESE CRITERIAS */
/* 1. LIBNAME SHOULD NOT BE MORE THAN 8 CHARACTERS LONG */
/* 2. IT MUST START WITH AN ALPHABET OR AN UNDERSCORE ONLY */
/* 3. IT MUST BE FOLLOWED WITH ALPHABET,UNDERSCORE AND NUMBERS ONLY */

/* TEST */
/* SESSION1 ----- YES */
/* SESSION_1 ----- NO */
/* SSN@1 ---- NO */
/* SSN 1 --- NO */
/* SSN_1 ---- YES */
/* 1_SSN ----- NO */
/* _SSN_1 ---- YES */

/* WHILE CREATING A DATASET AND A VARIABLE NAME, ARE WE FOLLOWING ANY CRITERIAS */

/* ANS- YES , WE DO */

/* YES, TO CREATE A DATASET AND VARIABLE NAME , WE MUST FOLLOW THESE CRITERIAS */
/* ====================================================================================== */

/* 1. LIBNAME SHOULD NOT BE MORE THAN 32 CHARACTERS LONG */
/* 2. IT MUST START WITH AN ALPHABET OR AN UNDERSCORE ONLY */
/* 3. IT MUST BE FOLLOWED WITH ALPHABET,UNDERSCORE AND NUMBERS ONLY */

/* TEST */
/* FIRST_NAME ------VARIABLE NAME---YES */
/* STU_ENQ_BANGALORE_2023 --- DATASET NAME --- YES */
/* CUSTOMER-ID ---- VARIABLE NAME --- NO */
/* CUSTOMER_ID ---- VARIABLE NAME --- YES */

/* VARIABLE VALUES AND THE DATA TYPES */
/* =================================== */

/* VARIABLES ARE 2 TYPES */
/* 1. CHARACTER */
/* 2. NUMERIC */
/*  */
/* VARIABLE LENGTH */
/* 1. CHARACTER VARIABLE LENGTH -  */
/* 	DEFAULT IS 8 */
/* 	MINIMUM IS 1 */
/* 	MAXIMUM IS 32,767 */
/* 2. NUMERIC VARIABLE LENGTH - */
/* 	DEFAULT IS 8 BYTES */
/* 	WHICH IS EQUAL TO 16-17 DIGITS */

DATA STU_DETAILS;
INPUT STU_NAME $ AGE EDUCATION $ COURSE $ ;
CARDS;
ASHOK 40 BTECH MPIDS
PRITIDHARA 25 MTECH MPIDS
RAJAT 26 BTECH MPAA
MRUTYUNJAY 28 MBA MPIDS
;
RUN;

PROC PRINT DATA=STU_DETAILS;
RUN;

DATA STU_DETAILS;
INPUT STU_NAME : $20. AGE EDUCATION $ COURSE $ ;
CARDS;
ASHOK 40 BTECH MPIDS
PRITIDHARA 25 MTECH MPIDS
RAJAT 26 BTECH MPAA
MRUTYUNJAY 28 MBA MPIDS
;
RUN;

PROC PRINT DATA=STU_DETAILS;
RUN;

/* IMPORTING AND EXPORTING DATA FROM TXT FILE */

/* HOW TO READ DATA FROM A TXT FILE USING PROC IMPORT */
/* ======================================================== */
OPTIONS VALIDVARNAME=V7;
/* TO READ DATA AS PER SAS NAMING CRITERIA */

PROC IMPORT OUT=SSN1.MED_2023
            DATAFILE='/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/MED_2023.txt'
            DBMS=DLM REPLACE;
            DELIMITER='|';
RUN;

            
/* HOW TO WRITE DATA TO A TXT FILE USING PROC EXPORT */
/* ======================================================== */

PROC EXPORT DATA=SSN1.MED_2023
            OUTFILE='/home/debendra330/BATCH_202301/SESSION_1/A4.SAS_OUTPUT/MED_2023.txt'
            DBMS=DLM REPLACE;
            DELIMITER=',';
RUN;


/* IMPORTING AND EXPORTING DATA FROM CSV FILE */
OPTIONS VALIDVARNAME=V7;
PROC IMPORT OUT=SSN1.MED_2023_CSV
            DATAFILE='/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/MED_2023.csv'
            DBMS=CSV REPLACE;
            DELIMITER=',';
RUN;

PROC EXPORT DATA=SSN1.MED_2023 
            OUTFILE='/home/debendra330/BATCH_202301/SESSION_1/A4.SAS_OUTPUT/MED_2023.csv'
            DBMS=CSV REPLACE;
RUN;

/* IMPORTING AND EXPORTING DATA FROM EXCEL FILE */
OPTIONS VALIDVARNAME=V7;
PROC IMPORT OUT=SSN1.MED_2023_EXCEL
            DATAFILE='/home/debendra330/BATCH_202301/SESSION_1/A1.RAW_DATA/MED_2023.xlsx'
            DBMS=XLSX REPLACE;
            SHEET='MED_AUSTRALIA';
RUN;

PROC EXPORT DATA=SSN1.MED_2023
            OUTFILE='/home/debendra330/BATCH_202301/SESSION_1/A4.SAS_OUTPUT/MED_2023.xlsx'
            DBMS=XLSX REPLACE;
            SHEET='MED_2023_AUS';
RUN;


/* HOW TO DESCRIBE A DATASET AND LIBRARY */
/* =========================================== */

PROC PRINT DATA=SSN1.STAFF;
RUN;

PROC CONTENTS DATA=SSN1.STAFF;
RUN;

PROC CONTENTS DATA=SSN1.STAFF VARNUM;
RUN;

PROC CONTENTS DATA=SSN1.STAFF VARNUM SHORT;
RUN;

/*LAST_NAME FIRST_NAME EMP_CODE JOBTITLE DOJ SALARY*/

/* 1. WE USE PROC CONTENTS TO DESCRIBE THE DATASETS INTO 3 PARTS */
		/* 1. DATASET INFORMATION */
		/* 2. HOST ENGINE */
		/* 3. VARIABLES AND DATA TYPES */

/* 2. WE USE PROC CONTENTS WITH VARNUM AS AN OPTION TO GET THE VARIABLES NAME IN ORDER */

/* 3. WE USE PROC CONTENTS WITH VARNUM AND SHORT TO GET THE HEADERS LIST IN TEH DATASET */

/* TEST */

/* HOW TO DESCRIBE DATASET SSN1.MED_2023? */

PROC CONTENTS DATA=SSN1.MED_2023 VARNUM;
RUN;

/* HOW TO GET THE VARIABLES NAME ONLY IN THE DATASET */

PROC CONTENTS DATA=SSN1.MED_2023 VARNUM SHORT;
RUN;

/*
CUSTOMER_ID Company CARD_REG_DATE CARD_ACTIVE FIRST_USE_DTE 
firstSTOR TITLE GENDER max_spent DOB FTD Age STATE_CODE 
POST_CODE CUST_STAT Avgsize_spent CARD_STAT RGSTN_TYPE_IND 
NO_OF_TRIPS TOWN EMAIL_IND CONTACT_PREF Average_Qty_PER_ACC Spent_amount
*/

/* CAN WE STORE THE OUTPUT OF PROC CONTENTS */

PROC CONTENTS DATA=SSN1.MED_2023 VARNUM OUT=MED_2023_CONTENT;
RUN;

/* HOW TO DESCRIBE A LIBRARY? */
/* =============================== */

PROC CONTENTS DATA=SSN1._ALL_ NODS;
RUN;

PROC CONTENTS DATA=SSN1._ALL_ ;
RUN;

/* WE USE NODS AS AN OPTION TO AVOID DESCRIBING EACH DATASETS IN THE LIBRARY */

/* HOW TO CREATE A NEW DATASET FROM AN EXISTING DATASET */
/* =================================================== */

DATA STAFF;
SET SSN1.STAFF;
RUN;

DATA MED_2023;
SET SSN1.MED_2023;
RUN;

DATA WORK.MED_2023;
SET SSN1.MED_2023;
RUN;

/* WE USE SET STATEMENT TO READ DATA FROM ONE DATASET TO ANOTHER */

/* HOW TO COPY DATASETS FROM ONE LIBRARY TO ANOTHER */
/* ====================================================== */

PROC COPY IN=SSN1 OUT=WORK;
SELECT STAFF MED_2023_CSV;
RUN;

PROC COPY IN=SSN1 OUT=WORK;
RUN;

/* PROC DATASETS LIBRARY=WORK KILL; */
/* RUN; */







	
	

		
 

























































